AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 29

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'adsync.gemspec'
    - 'bin/adsync'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
